- name: tmux-v0.1.0.tar.gz
  version: 0.1.0
  url: https://github.com/alicemarple/dotfiles/releases/download/tmux-v0.1.0/tmux-v0.1.0.tar.gz
  confdir: ~/.config/xyz
- name: nvim-v0.1.0.tar.gz
  version: 0.1.0
  url: https://github.com/alicemarple/dotfiles/releases/download/nvim-v0.1.0/nvim-v0.1.0.tar.gz
  confdir: ~/.config/xyz
